-- Dulces Celis · esquema inicial para Supabase
create extension if not exists pgcrypto;

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  slug text not null unique
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  categoria_id bigint not null references public.categorias(id) on delete restrict,
  nombre text not null,
  descripcion text not null default '',
  precio numeric(12,2) not null check (precio >= 0),
  dias_anticipacion integer not null default 1 check (dias_anticipacion >= 0),
  es_personalizable boolean not null default false,
  imagen_url text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_nombre text not null,
  cliente_whatsapp text not null,
  fecha_entrega date not null,
  detalles_json jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null check (total >= 0),
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'En Preparación', 'Entregado')),
  created_at timestamptz not null default now()
);

create index if not exists productos_categoria_idx on public.productos(categoria_id);
create index if not exists productos_activo_idx on public.productos(activo);
create index if not exists pedidos_created_idx on public.pedidos(created_at desc);

alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "catalogo publico lectura categorias" on public.categorias;
create policy "catalogo publico lectura categorias" on public.categorias for select to anon, authenticated using (true);

drop policy if exists "catalogo publico lectura productos" on public.productos;
create policy "catalogo publico lectura productos" on public.productos for select to anon, authenticated using (true);

drop policy if exists "catalogo publico actualiza productos" on public.productos;
create policy "catalogo publico actualiza productos" on public.productos for update to anon, authenticated using (true) with check (true);

drop policy if exists "pedidos publicos insercion" on public.pedidos;
create policy "pedidos publicos insercion" on public.pedidos for insert to anon, authenticated with check (true);

drop policy if exists "pedidos panel lectura" on public.pedidos;
create policy "pedidos panel lectura" on public.pedidos for select to anon, authenticated using (true);

drop policy if exists "pedidos panel actualizacion" on public.pedidos;
create policy "pedidos panel actualizacion" on public.pedidos for update to anon, authenticated using (true) with check (true);

drop policy if exists "pedidos panel eliminacion" on public.pedidos;
create policy "pedidos panel eliminacion" on public.pedidos for delete to anon, authenticated using (true);

grant select on public.categorias, public.productos to anon, authenticated;
grant insert, select, update, delete on public.pedidos to anon, authenticated;
grant update on public.productos to anon, authenticated;

insert into public.categorias (nombre, slug) values
  ('Marquesas', 'marquesas'),
  ('Galletas & Brownies', 'galletas-brownies'),
  ('Tortas Clásicas', 'tortas-clasicas'),
  ('Tortas Temáticas', 'tortas-tematicas')
on conflict (slug) do update set nombre = excluded.nombre;

insert into public.productos (categoria_id, nombre, descripcion, precio, dias_anticipacion, es_personalizable, imagen_url, activo)
select c.id, p.nombre, p.descripcion, p.precio, p.dias_anticipacion, p.es_personalizable, p.imagen_url, true
from (values
  ('marquesas', 'Marquesa de parchita', 'Postre frío de parchita en capas, presentado en envase individual.', 8.00, 1, false, 'assets/catalogo/marquesa-parchita.jpeg'),
  ('marquesas', 'Marquesa de chocolate', 'Postre frío de chocolate en capas, presentado en envase individual.', 8.00, 1, false, 'assets/catalogo/marquesa-chocolate.jpeg'),
  ('galletas-brownies', 'Galletas con chispas', 'Galletas horneadas con chispas de chocolate.', 6.00, 2, false, 'assets/catalogo/galletas-chispas.jpeg'),
  ('galletas-brownies', 'Galletas de doble chocolate', 'Galletas de chocolate con trozos y chispas de chocolate.', 7.00, 2, false, 'assets/catalogo/galletas-chocolate.jpeg'),
  ('galletas-brownies', 'Brownie individual', 'Brownie húmedo con chispas de chocolate.', 5.00, 2, false, 'assets/catalogo/brownie.jpeg'),
  ('tortas-clasicas', 'Torta de fresas con crema', 'Torta decorada con crema y fresas.', 35.00, 2, false, 'assets/catalogo/torta-fresas.jpeg'),
  ('tortas-clasicas', 'Torta de chocolate ganache', 'Torta de chocolate con acabado de ganache.', 40.00, 2, false, 'assets/catalogo/torta-chocolate.jpeg'),
  ('tortas-tematicas', 'Torta temática', 'Diseño personalizado: dinosaurios, Banban, Halloween u otro motivo.', 45.00, 4, true, 'assets/catalogo/torta-tematica.jpeg')
) as p(slug, nombre, descripcion, precio, dias_anticipacion, es_personalizable, imagen_url)
join public.categorias c on c.slug = p.slug
where not exists (select 1 from public.productos x where x.nombre = p.nombre);
